### PR TITLE
[AAP-17462] Display error on Create activation form

### PR DESCRIPTION
**Pull request by lgalis**
Add eda error adapter:
Screenshot from 2023-11-09 11-04-14
Screenshot from 2023-11-09 10-48-24

### CODE REVIEW

**Comment by nixocio** [comment]
@lgalis Do we want to show the object with the error at form level or just the error itself?

Just ```No controller token specified```

For hub we did like this 

image

**Comment by lgalis** [comment]
@nixocio - I agree that on the message should be displayed - the problem is that at the moment, the backend return is {"errors":"{'errors': 'No controller token specified'}"} - this will be fixed in the backend to instead be just {'errors': 'No controller token specified'}, and then the UI will display only the message. The UI would stay as it is in this PR.

**Comment by jamestalton** [comment]
The framework supports showing an error on a specific field if the backend returns the field name and error as part of the payload.

```
{
  "name": [
    "A project with this name already exists."
  ]
}
```

Screenshot 2023-11-08 at 11 52 24 AM

Would it make sense for the backend to return the error on the input field?

**Comment by lgalis** [comment]
@jamestalton - the controller token in the image above is not an input field error. I am waiting for a backend PR to change the return to mark the error as such, then I will update this PR to display the error value only.

**Review by nixocio — DISMISSED** [review]

**Comment by lgalis** [comment]
Updated after the latest API changes to return: 
field errors:
{
        name: ['Name is required'],
        email: ['Email is invalid'],
}

non field errors:
{"non_field_errors":["No controller token specified"]}

**Review by nixocio — APPROVED** [review]
@lgalis Good job.

**Pull request merged**
