### PR TITLE
Workflow Job Ouput 

### PR DESCRIPTION
**Pull request by AlexSCorey**
This addresses:
https://issues.redhat.com/browse/AAP-19089
https://issues.redhat.com/browse/AAP-19090
https://issues.redhat.com/browse/AAP-21460
https://issues.redhat.com/browse/AAP-21520

It adds status, and elapsed time decorators to the nodes in the job output as the status of the node is update via websockets.  

websockets

### CODE REVIEW

**Comment by AlexSCorey** [comment]
@akus062381 @vishsanghishetty

**Comment by akus062381** [comment]
Testing currently, and I am running a wfjt, the decorate for Debug 50 isn't showing
image

**Comment by akus062381** [comment]
Question- while the different nodes are in the process of running, should we see the time counting forward on each individual node? or should we see "elapsed time" as shown here (with the elapsed time only being displayed once the workflow is complete?)
image

**Comment by akus062381** [comment]
I saw that while a wfjt is in the process of running, switching to the Details view of the job and looking at Duration- the time first shows as '0 seconds' before switching over to the actual progressed time

**Comment by akus062381** [comment]
I noticed that sometimes, all nodes will show that they are finished running, but the job time counter continues ticking, and the status of the job shows Running until I clicked refresh on the browser

image

**Review by akus062381 — CHANGES_REQUESTED** [review]
I made some comments on the PR about little bugs I was seeing.

**Review by marshmalien — APPROVED** [review]

**Pull request merged**
