### PR TITLE
Bug fix:  Show deleted icon when resource has been deleted

### PR DESCRIPTION
**Pull request by marshmalien**
Screenshot 2024-03-26 at 3 18 16 PM

### CODE REVIEW

**Comment by jerabekjiri** [comment]
Nice fix :+1: 
Screenshot from 2024-03-27 11-45-44

**Comment by jerabekjiri** [comment]
So I can add a new node to the `Deleted` node and then saving throws this error. Maybe we could disable or hide 'Add step and link' for deleted nodes?

Screenshot from 2024-03-27 11-50-39

**Comment by marshmalien** [comment]
> So I can add a new node to the Deleted node and then saving throws this error. Maybe we could disable or hide Add step and link option for deleted nodes?

Good find. Let me look into that error message. The old UI allows us to add nodes to deleted nodes, so I'm going to try get that working.

**Review by jerabekjiri — APPROVED** [review]
LGTM :+1:

**Pull request merged**
