### PR TITLE
Add User/Team Access tabs to Job templates

### PR DESCRIPTION
**Pull request by keithjgrant**
Screenshot 2024-05-06 at 1 26 31 PM

Screenshot 2024-05-06 at 1 26 42 PM

### CODE REVIEW

**Comment by vishsanghishetty** [comment]
trying to add teams using the toolbar filters in the modal
image

trying to add teams using the table row item in the modal
image

**Comment by vishsanghishetty** [comment]
QA'ed this locally, 
I was able to 

1. create a JT
2. Select the team(s) and give access to the Job Template I created ✅ 
3. Select the roles(s) to apply to the Job Template I created  ✅ 
4. Select the user(s) and give access to the Job Template I created  ✅ 
5. Select the roles(s) to apply to the Job Template I created  ✅

**Review by vishsanghishetty — APPROVED** [review]
lgtm

**Review by vidyanambiar — APPROVED** [review]
Looks great ✨ 

Could we get some component tests added for the access tabs?

**Pull request merged**
