### PR TITLE
[AAP-27781] Fix EDA credential types test

### PR DESCRIPTION
**Pull request by ZitaNemeckova**
Steps to reproduce failures:
- create credential names so there's at least 10 of them
- run tests
Before:
```
  1) EDA Credentials Type - Create, Edit, Delete
       can edit a credential type:
     AssertionError: Timed out retrying after 30000ms: Expected to find content: 'E2E Credential TypeSUTh' within the selector: 'tr' but never did.
      at Context.eval (webpack://@ansible/ansible-ui/./cypress/support/awx-commands.ts:350:0)

  2) EDA Credentials Type - Create, Edit, Delete
       can delete a credential type:
     AssertionError: Timed out retrying after 30000ms: Expected to find content: 'E2E Credential TypeOJVQ' within the selector: 'tr' but never did.
      at Context.eval (webpack://@ansible/ansible-ui/./cypress/support/awx-commands.ts:350:0)

  3) EDA Credentials Type - Create, Edit, Delete
       cannot delete a credential type if already in use:
     AssertionError: Timed out retrying after 30000ms: Expected to find content: 'E2E Credential TypePxmd' within the selector: 'tr' but never did.
      at Context.eval (webpack://@ansible/ansible-ui/./cypress/support/awx-commands.ts:350:0)

  4) EDA Credentials Type - Create, Edit, Delete
       cannot edit a credential type if already in use:
     AssertionError: Timed out retrying after 30000ms: Expected to find content: 'E2E Credential TypeeEBE' within the selector: 'tr' but never did.
      at Context.eval (webpack://@ansible/ansible-ui/./cypress/support/awx-commands.ts:350:0)

  5) EDA Credentials Type - Create, Edit, Delete
       can bulk delete credential types:
     AssertionError: Timed out retrying after 30000ms: Expected to find content: 'E2E Credential TypeewAU' within the selector: 'tr' but never did.
      at Context.eval (webpack://@ansible/ansible-ui/./cypress/support/awx-commands.ts:350:0)
```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  credential-type-crud.cy.ts               09:33       11        6        5        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     09:33       11        6        5        -        -  

After:

       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  credential-type-crud.cy.ts               01:41       11       11        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        01:41       11       11        -        -        -  

- Add filter to Credential Types page
- Every test filters for the Credential Type before trying to click/select it
- Bulk delete only one item as there's no guarantee that two items can be correctly filtered

Fixes https://issues.redhat.com/browse/AAP-27781

### CODE REVIEW

**Comment by AlexSCorey** [comment]
@ZitaNemeckova have we tested this downstream, on the testing instance and on the vm?

**Review by AlexSCorey — APPROVED** [review]
Looks good.  I just want to be sure we've tested these things downstream on both deployment types.

**Comment by jlmitch5** [comment]
@vidyanambiar will run downstream and if it passes we will merge

**Review by vidyanambiar — APPROVED** [review]
Tested on dev server + VM. ✅

**Pull request merged**
