### PR TITLE
[UXD][AAP-25027] AWX - updates to Hosts section breadcrumbs & headers

### PR DESCRIPTION
**Pull request by tiyiprh**
https://issues.redhat.com/browse/AAP-25027

Updates to Hosts section areas breadcrumbs and headers

### CODE REVIEW

**Comment by acruzgon** [comment]
i believe this PR can be closed in favor of https://github.com/ansible/ansible-ui/pull/2722

**Comment by tiyiprh** [comment]
> i believe this PR can be closed in favor of #2722

@acruzgon Do I need to make the changes that I made here in #2722 as well?

**Comment by tiyiprh** [comment]
@daphnemaeve The failures don't seem related to my PR

**Comment by daphnemaeve** [comment]
> @daphnemaeve The failures don't seem related to my PR

Agreed, I'll re-run checks!

**Comment by tiyiprh** [comment]
Closing in favor of #2722 as the changes in this PR are also in the other PR.

**Pull request closed without merging**
