### PR TITLE
Hub: useGetFn

### PR DESCRIPTION
**Pull request by himdel**
Needed by #1415,
Issue: AAH-2994

---

The pattern for detail screens doing only one GET request is essentially...

```js
import { useGet } from '@frontend/common/crud/useGet';

const { data, error, isLoading, refresh } = useGet<MyType>(hubAPI`/url`);

// process data, error, ...
```

But that pattern breaks when multiple GET requests are necessary, if some are optional, if some need a value from a previous request, or when you need to query everything in an array.

This introduces a `useGetFn`, which allows for a `function => Promise` parameter instead of the url, and is really just a thin wrapper around `useSwr` with a `useGet`-compatible error handling.

```js
import { useGetFn } from '@frontend/hub/useGetFn';
import { requestGet } from '@frontend/common/crud/Data';

const { data, error, isLoading, refresh } = useGetFn<MyType>('unique-identifier-for-caching',
  (signal?: AbortSignal) => requestGet(hubAPI`/url`, signal),
);

// process data, error, ...
```

^ both examples should do the same thing.

---

More complex examples:

2 requests:

```js
const { data1, error1 } = useGet(url1);
const { data2, error2 } = useGet(url2);
// manually reconcile cases like data1 && error2...

OR

const { data, error } = useGetFn('unique', () => Promise.all([
  requestGet(url1),
  requestGet(url2),
]));
```

dependent requests:

```js
const { data1, error1 } = useGet(url1);
const { data2, error2 } = useGet(data1 && !error1 ? data1.myURL : null);

OR

const { data, error } = useGetFn('unique', async () => {
  const { myURL } = await requestGet(url1);
  return requestGet(myURL);
]));
```

taks detail:

```js
function loadContent(taskId?: string) {
  if (!taskId) {
    return Promise.reject();
  }

  return requestGet<Task>(pulpAPI`/tasks/${taskId}/`).then((task) => {
    const allRelatedTasks = [];
    let parentTask: Task | null = null;
    const childTasks: Task[] = [];
    const resources: TaskResource[] = [];

    if (task.parent_task) {
      const parentTaskId = parsePulpIDFromURL(task.parent_task);
      allRelatedTasks.push(
        parentTaskId &&
          requestGet<Task>(pulpAPI`/tasks/${parentTaskId}/`)
            .then((data) => {
              parentTask = data;
            })
            .catch(() => null)
      );
    }

    if (task.child_tasks.length) {
      task.child_tasks.forEach((child) => {
        const childTaskId = parsePulpIDFromURL(child);
        allRelatedTasks.push(
          childTaskId &&
            requestGet<Task>(pulpAPI`/tasks/${childTaskId}/`)
              .then((data) => {
                childTasks.push(data);
              })
              .catch(() => null)
        );
      });
    }

    if (task.reserved_resources_record.length) {
      task.reserved_resources_record.forEach((url) => {
        const id = parsePulpIDFromURL(url);
        const urlParts = url.replace(process.env.HUB_API_PREFIX + '/pulp/api/v3/', '').split('/');
        let resourceType = '';
        let pluginName = '';

        // pulp hrefs follow this pattern for resources added by plugins: /<resource name>/<plugin name>/<resource type>/<pk>/
        // Locks can be added on the entire resource (ex /repositories/) or on a specific instance of a resource (ex /repositories/ansible/ansible/123123/)
        if (urlParts.length >= 3) {
          // if the url has 3 or more segements, parse out the resource, plugin name, and resource type
          resourceType = `${urlParts[0]}: ${urlParts[2]}`;
          pluginName = urlParts[1];
        } else {
          // otherwise, just return the resource type
          resourceType = urlParts[0];
        }

        if (id) {
          allRelatedTasks.push(
            requestGet<{ name: string }>(url)
              .then((data) => {
                resources.push({
                  name: data.name,
                  type: resourceType,
                  pluginName,
                  url,
                });
              })
              .catch(() => null)
          );
        } else {
          resources.push({ type: resourceType, url });
        }
      });
    }

    return Promise.all(allRelatedTasks).then(() => {
      return {
        task,
        childTasks,
        parentTask,
        resources,
      };
    });
  });
}
```

```js
  const params = useParams<{ id: string }>();
  const { data, error, isLoading, refresh } = useGetFn<{
    childTasks: Task[];
    parentTask: Task | null;
    resources: TaskResource[];
    task: Task;
  }>(`task-details-${params.id}`, () => loadContent(params.id));
  const { task, childTasks, parentTask, resources } = data || {};
```

### CODE REVIEW

**Comment by himdel** [comment]
Cc @nixocio , @skochay330

**Review by nixocio — COMMENTED** [review]
hey @himdel at first look this looks great.

What about we move to this directory here https://github.com/ansible/ansible-ui/tree/a9ee33cd49722b5b6ce2886080d40034b04e032f/frontend/hub/common/api?

Also you did a great job explaining the usage on the body of the PR, what about adding an entry here https://github.com/ansible/ansible-ui/tree/a9ee33cd49722b5b6ce2886080d40034b04e032f/frontend/hub/common/api#readme
?

**Comment by jamestalton** [comment]
useGet underneath calls useGetRequest which
- Handles an abort controller for the request
- Handles 401 responses to navigate to '/login'

**Review by skochay330 — APPROVED** [review]
Works great, thank you!

**Comment by himdel** [comment]
Thanks :),
moved to `frontend/hub/common/api/useGetFn`,
added a `useGet` & `useGetFn` example to `frontend/hub/common/api/README.md`,
changed the fetcher function to accept `(signal?: AbortSignal)` allowing us to pass it to `requestGet(url, signal)`,
and catching any `RequestError` with `statusCode === 401` to navigate to login.

**Review by nixocio — APPROVED** [review]
LGTM, good job @himdel

**Pull request merged**
