### PR TITLE
RBAC UIs for Hub

### PR DESCRIPTION
**Pull request by vidyanambiar**
1. Team/User access tabs for EE, Remotes, Namespaces, Repos
    - [AAP-16644](https://issues.redhat.com/browse/AAP-16644)
    - [AAP-27882](https://issues.redhat.com/browse/AAP-27882)
    - [AAP-27887](https://issues.redhat.com/browse/AAP-27887)
    - [AAP-27888](https://issues.redhat.com/browse/AAP-27888)
2. User roles: [AAP-28446](https://issues.redhat.com/browse/AAP-28446)
    - Since there is no upstream implementation of users pages, this can be tested with the following steps:
Get the user ID you want to test with using <server>/api/galaxy/_ui/v2/users/
Access `https://localhost:4102/access/users/<user_id_from_above>/roles`
3. Team roles: [AAP-28442](https://issues.redhat.com/browse/AAP-28442)
    - Since there is no upstream implementation of team pages, this can be tested with the following steps:
Get the user ID you want to test with using <server>/api/galaxy/_ui/v2/teams/
Access `https://localhost:4102/access/teams/<team_id_from_above>/roles`
4. Hub Roles UI: [AAP-19958](https://issues.redhat.com/browse/AAP-19958)
    - List of roles, CRUD on custom roles
    - There is a known API bug with some built-in roles being indicated as editable

Regarding 2 and 3 from above:
Since there is no upstream implementation of users pages, this can be tested with the following steps:
Get the user ID you want to test with using <server>/api/galaxy/_ui/v2/users/
Access https://localhost:4102/access/users/<user_id_from_above>/roles

```
export HUB_SERVER=
export HUB_API_PREFIX=/api/galaxy
npm run hub
```

### CODE REVIEW

**Comment by vishsanghishetty** [comment]
@vidyanambiar @nixocio great work! 🚀

**Comment by kialam** [comment]
I pulled this down locally and tested adding and removing teams/users for Remotes, Repositories, Namespaces, and Execution Environments ([AAP-16644](https://issues.redhat.com/browse/AAP-16644)
[AAP-27882](https://issues.redhat.com/browse/AAP-27882)
[AAP-27887](https://issues.redhat.com/browse/AAP-27887)
[AAP-27888](https://issues.redhat.com/browse/AAP-27888))

Everything worked except for EE, which is a known API bug. 👍

**Comment by ZitaNemeckova** [comment]
🟢 Tested without API changes. All pages showed an error state as expected 

🟢 Tested with API changes:
   🟢 Add User
   🟢 Add Team
   🟢 Remove an user via row action
   🟢 Remove a team via row action
   🟢 Bulk delete users
   🟢 Bulk delete teams
   🟢 Filtering
   🟢 Sorting Teams

🔴 Pagination is broken - All items are shown on the page (even 148 items)
🔴  User Access Tab -> sort table by first name -> 400 bad request `{"detail":"RoleUserAssignment has no field named 'first_name'"}`
🔴  User Access Tab -> sort table by last name -> 400 bad request `{"detail":"RoleUserAssignment has no field named 'last_name'"}`
🔴 Team Access Tab and User Access tab share list/card/tile settings (if you chose cards on User Access tab it changes on Team Access tab as well) - minor
Note: EE testing skipped  

No major issue found.

**Review by ZitaNemeckova — APPROVED** [review]
Double checked with the team 👍

**Pull request merged**
