### PR TITLE
implemented view for workflow job templates survey

### PR DESCRIPTION
**Pull request by resoluteCoder**
- Added a quick bug fix / implementations for the workflow job templates survey view
- Added ability to submit workflow job template via api

### CODE REVIEW

**Comment by jerabekjiri** [comment]
I'm getting this on survey with text field
Screenshot from 2024-04-16 12-15-18

**Comment by jerabekjiri** [comment]
also I think we should show default values. In the screenshot, multi select doesn't show any default options, same with text input? @resoluteCoder wdyt 
Screenshot from 2024-04-16 12-13-33

**Comment by resoluteCoder** [comment]
@jerabekjiri  Great catches here. I fixed both issues. The last one was due to a merge conflict gone wrong :sweat_smile:

**Comment by jerabekjiri** [comment]
Old UI has this question icon with tooltip description, should we add this too? wdyt @resoluteCoder 
Screenshot from 2024-04-15 18-44-59

**Review by jerabekjiri — APPROVED** [review]
LGTM, great work! :+1:

**Pull request merged**
