### PR TITLE
[AAP-23598] Fix slow schedule toggle

### PR DESCRIPTION
**Pull request by prat98**
This PR addresses AAP-23598 which points out an issue with a slow schedule toggle. The fix updates the item instead of refreshing the whole view upon successfully patching the resource.

Before:

https://github.com/ansible/ansible-ui/assets/112966709/e8f725bb-5f0e-42b0-97b9-7a8aca56ffb7

After:

https://github.com/ansible/ansible-ui/assets/112966709/83a33a69-13d9-4bac-bdd1-fe0f6c19dcf2

### CODE REVIEW

**Comment by vishsanghishetty** [comment]
QA'ed locally creating all types of schedules, works smoothly! nice improvements @prat98 👏 

https://github.com/ansible/ansible-ui/assets/95239214/2e03bb3a-1579-4c24-87a1-c7376e5c2163

**Review by vishsanghishetty — APPROVED** [review]
lgtm

**Review by akus062381 — APPROVED** [review]
@prat98 thanks so much for fixing this, looks great

**Review by nixocio — APPROVED** [review]
👍

**Pull request merged**
