### PR TITLE
Job output websockets

### PR DESCRIPTION
**Pull request by keithjgrant**
Add live job events to job output screen from websocket messages.

* websocket events are added to the jobEvents object
* missing/skipped event indexes are tracked in a `missingEvents` object
* after a 2.5 second delay, any missing events that the UI attempts to render (still haven't come in via websockets) are fetched via API to fill in the gaps

### CODE REVIEW

**Review by vidyanambiar — COMMENTED** [review]
I have a template that uses the Demo Project:
image

When I launch the template the job output starts and appears for a few moments before I see this failure:
 
image

**Comment by keithjgrant** [comment]
> When I launch the template the job output starts and appears for a few moments before I see this failure:

Fixed!

**Review by AlexSCorey — APPROVED** [review]
This looks good to me.

**Review by vidyanambiar — APPROVED** [review]
lgtm!

**Review by akus062381 — APPROVED** [review]

**Pull request merged**
