### PR TITLE
Cypress upgraded to v13.1.0

### PR DESCRIPTION
**Pull request by vidyanambiar**
Version 13 of Cypress contains a new feature called 'Test Replay' which promises easy debugging of CI test failures in Cypress Cloud.

### CODE REVIEW

**Comment by vidyanambiar** [comment]
CI checks fail on `npm ci` due to an unresolved peer dependency. See thread: https://redhat-internal.slack.com/archives/C027K1897U4/p1694536513212149

**Comment by keithjgrant** [comment]
> Any recommendations?

I'd prefer to wait for the release rather than get in the habit of using --force or --legacy-peer-deps. I don't want to get stuck in a position where we could end up relying on those flags indefinitely if some dependency doesn't update

**Comment by keithjgrant** [comment]
oh, it looks like the released that change with v2.2.5!

**Comment by vidyanambiar** [comment]
@keithjgrant Thanks! I've updated`@4tw/cypress-drag-drop` to 2.2.5 👍

**Review by nixocio — APPROVED** [review]
👍

**Review by lgalis — APPROVED** [review]

**Pull request merged**
