### PR TITLE
add facts test to regular inventory

### PR DESCRIPTION
**Pull request by RedOrNot**

### CODE REVIEW

**Comment by RedOrNot** [comment]
ticket: https://issues.redhat.com/browse/AAP-24973

**Comment by vishsanghishetty** [comment]
@RedOrNot 
ESLint failed on this PR, please check
`Error: [tsc] cypress/e2e/awx/resources/hosts.cy.ts(61,5): error TS2554: Expected 2 arguments, but got 1.`

**Comment by RedOrNot** [comment]
ya I'm getting the mails about filed runs
thanks

**Comment by MilanPospisil** [comment]
Im going to continue on this PR and possibly merge it, since we are short on time and Or is probably outside of her working hours. @RedOrNot

**Review by ZitaNemeckova — APPROVED** [review]

**Pull request merged**
