### PR TITLE
HUB Approvals E2E

### PR DESCRIPTION
**Pull request by jamestalton**

### CODE REVIEW

**Review by akus062381 — CHANGES_REQUESTED** [review]
I would like to avoid having one big test that asserts lots of different functionality in it. Let's keep the tests separate please. Thanks!

**Comment by jamestalton** [comment]
> I would like to avoid having one big test that asserts lots of different functionality in it. Let's keep the tests separate please. Thanks!

This creates one collection, which is the slow part of the tests.

The previous tests would

- Verify Approve
- Verify Reject
- Verify Approve then reject (Which is testing the approve and rejects again)
- Verify Reject then approve(Which is testing the approve and rejects again)

This instead checks all that by approve, then reject, then approve.
Not really any different than what the original tests tested, just tests it more efficiently.

**Comment by akus062381** [comment]
@jamestalton I understand that your goal is speed and optimization of the tests. I am just trying to think about how we can best verify the UI functionality the way a user is likely to use it, while also optimizing for speed? 

What if we have two separate tests:
1. can upload a new collection, approve,  view import logs
2. can upload a new collection, reject, and view import logs

I feel like this is a bit more in line with how a user would be likely to use this feature...? 
Thanks for your consideration!

**Review by akus062381 — APPROVED** [review]
This looks good, thanks for all your hard work on it!

**Pull request merged**
