### PR TITLE
Enhanced table columns

### PR DESCRIPTION
**Pull request by jamestalton**
- JSDoc for table column options
- Adds options for displaying columns in the expanded row

### CODE REVIEW

**Review by vidyanambiar — CHANGES_REQUESTED** [review]
Expanded row: 
- In some cases the description appears above the Created and Modified fields (Organizations) and other cases it appears below (Projects, Templates..). Could we update it to always show at the top for consistency?
image

- Perhaps a "Description" title will be good to distinguish it from other fields. 
image

**Comment by jamestalton** [comment]
The description, when coming from a column should always show up above the details. This will give it prominence under the item and allow the description to fill the whole horizontal space.

If a developer adds "expandedRow" content specifically to a table (i.e. a chart), it will show under the details that are generated from the columns.

In the case of the project screenshot above, the description is being added by the "expandedRow" on the table and not as a column with description.

We will need a follow up PR to address the use of "expandedRow" to show descriptions.

**Comment by vidyanambiar** [comment]
I think a "Description" title would be helpful in such cases to distinguish this field from the other fields. In the screenshot above the description looks like an extension of the "Created" field which could be confusing to users.

**Comment by jamestalton** [comment]
Updated the rest of the tables such as projects to use the column description.

We can add a description title to it, but since it now shows above the other details, i'd like to try it with out the title first.

**Review by vidyanambiar — APPROVED** [review]

**Pull request merged**
