### PR TITLE
Filtering superusers from the user lookup step in role assignment wizards

### PR DESCRIPTION
**Pull request by vidyanambiar**
[AAP-23939](https://issues.redhat.com/browse/AAP-23939)

Super users (System administrators) do not need to be assigned specific roles on resources as they already have all the available permissions.

This PR filters superusers out of the user lookup wizard step when adding a user to a resource (AWX/EDA)

Note: In case of EDA, this filter does not appear to be supported yet on the API

image

### CODE REVIEW

**Review by lgalis — APPROVED** [review]
LGTM for AWX. EDA will need the backend changes merged to support the filtering used here.

**Comment by vidyanambiar** [comment]
Thanks for reviewing, @lgalis. Doston is working on getting the EDA backend updated to support this filter [AAP-26690](https://issues.redhat.com/browse/AAP-26690)

**Comment by vishsanghishetty** [comment]
@vidyanambiar tried testing this

1. created a super user `supuser` on AWX development environment
2. when trying to search for the above user in the user lookup wizard, I am seeing this screenshot. It is as expected super users are filtered
image

**Review by vishsanghishetty — APPROVED** [review]

**Comment by vidyanambiar** [comment]
@vishsanghishetty Thanks for reviewing! To answer your question, the `Select at least one user` is expected on `Next` since this wizard is for adding users to the organization.

**Comment by vishsanghishetty** [comment]
> @vishsanghishetty Thanks for reviewing! To answer your question, the `Select at least one user` is expected on `Next` since this wizard is for adding users to the organization.

thanks for confirming Vidya!

**Pull request merged**
